name: subsonic_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  crypto: ^3.0.5
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: '>=4.0.0 <5.0.0'

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  http_mock_adapter: ^0.6.1
