name: Dart

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Check for uncommitted changes
        run: |
          git diff --exit-code

      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze

      - name: Run tests
        run: dart test